In [4]:
import numpy as np
from PIL import Image

# ---------------- Q1 ----------------

In [7]:
# a
arr = np.array([1, 2, 3, 6, 4, 5])
print("reversed:", arr[::-1])

reversed: [5 4 6 3 2 1]


In [8]:
# b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("using flatten():", array1.flatten())
print("using ravel():", np.ravel(array1))

using flatten(): [1 2 3 2 4 5 1 2 3]
using ravel(): [1 2 3 2 4 5 1 2 3]


In [9]:
# c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("are equal:", np.array_equal(arr1, arr2))

are equal: True


In [10]:
# d
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_freq_x = np.bincount(x).argmax()
most_freq_y = np.bincount(y).argmax()
print("Most frequent in x:", most_freq_x, ", Indices:", np.where(x == most_freq_x)[0])
print("Most frequent in y:", most_freq_y, ", Indices:", np.where(y == most_freq_y)[0])

Most frequent in x: 1 , Indices: [0 5 7 8 9]
Most frequent in y: 1 , Indices: [0 1 2]


In [11]:
# e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("sum:", gfg.sum())
print("row sum:", gfg.sum(axis=1))
print("column sum:", gfg.sum(axis=0))

sum: 45
row sum: [[14]
 [16]
 [15]]
column sum: [[20  9 16]]


In [12]:
# f
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("diagonal sum:", np.trace(n_array))
print("eigenvalues:", np.linalg.eigvals(n_array))
vals, vecs = np.linalg.eig(n_array)
print("eigenvectors:\n", vecs)
print("inverse:\n", np.linalg.inv(n_array))
print("determinant:", np.linalg.det(n_array))

diagonal sum: 176
eigenvalues: [98.16835147 28.097044   49.73460452]
eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant: 137180.0000000001


In [15]:
# g
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
print("matrix prod 1:\n", np.dot(p1, q1))
print("covar of prod 1:", np.cov(np.dot(p1, q1)))

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
print("matrix prod 2:\n", np.dot(p2, q2))
print("covar of prod 2:", np.cov(np.dot(p2, q2)))

matrix prod 1:
 [[16 19]
 [26 31]]
covar of prod 1: [[ 4.5  7.5]
 [ 7.5 12.5]]
matrix prod 2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
covar of prod 2: [[ 54.33333333  89.16666667 158.83333333]
 [ 89.16666667 146.33333333 260.66666667]
 [158.83333333 260.66666667 464.33333333]]


In [16]:
# h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("inner prod:", np.inner(x[0], y[0]))
print("outer prod:\n", np.outer(x, y))
cartesian = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print("cart prod:\n", cartesian)

inner prod: 17
outer prod:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
cart prod:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


# ---------------- Q2 ----------------

In [18]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
print("abs:", np.abs(array))
flat = array.flatten()
print("percentiles (flat):", np.percentile(flat, [25, 50, 75]))
print("oercentiles (cols):", np.percentile(array, [25, 50, 75], axis=0))
print("percentiles (rows):", np.percentile(array, [25, 50, 75], axis=1))
print("mean:", flat.mean(), "Median:", np.median(flat), "std dev:", flat.std())
print("mean (cols):", array.mean(axis=0), "median (cols):", np.median(array, axis=0))
print("mean (rows):", array.mean(axis=1), "median (rows):", np.median(array, axis=1))

abs: [[1 2 3]
 [4 5 6]]
percentiles (flat): [-3.5 -0.5  2.5]
oercentiles (cols): [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
percentiles (rows): [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
mean: -0.5 Median: -0.5 std dev: 3.8622100754188224
mean (cols): [-1.5  1.5 -1.5] median (cols): [-1.5  1.5 -1.5]
mean (rows): [ 0.66666667 -1.66666667] median (rows): [ 1. -4.]


In [19]:
# b
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("floor:", np.floor(a))
print("ceiling:", np.ceil(a))
print("truncated:", np.trunc(a))
print("rounded:", np.round(a))

floor: [-2. -2. -1.  0.  1.  1.  3.]
ceiling: [-1. -1. -0.  1.  2.  2.  3.]
truncated: [-1. -1. -0.  0.  1.  1.  3.]
rounded: [-2. -2. -0.  0.  2.  2.  3.]


# ---------------- Q3 ----------------

In [20]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("sorted:", np.sort(array))
print("sorted indices:", np.argsort(array))
print("4 smallest:", np.sort(array)[:4])
print("5 largest:", np.sort(array)[-5:])

array2 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("integer elements:", array2[array2 == array2.astype(int)])
print("float elements:", array2[array2 != array2.astype(int)])

sorted: [ 10  16  16  52  54  62 453]
sorted indices: [0 3 4 1 5 2 6]
4 smallest: [10 16 16 52]
5 largest: [ 16  52  54  62 453]
integer elements: [1. 2. 3. 2.]
float elements: [1.2 2.2]


# ---------------- Q4 ----------------

In [22]:
def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:
        np.savetxt("gray_image.txt", arr, fmt='%d')
    else:
        np.savetxt("rgb_image.txt", arr.reshape(-1, arr.shape[2]), fmt='%d')
    return arr